package core;

public final class Schema {
	// super class of other schemas
	public static class Source {
		public static String keyword;
		public static String singleComment;
		public static String mutiComment;
		public static String tab;
		public String getKeyword() {
			return keyword;
		}
		public String getSingleComment() {
			return singleComment; 
		}
		public String getMutiComment() {
			return mutiComment;
		}
	}
	
	// HTML sections, pretty bad to process like this
	public final static String HTML_title = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\"><head><meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\" /><title>";
	public final static String title_HTML_size = "</title><style type=\"text/css\">* {margin:0px;padding:0px;font-family:Microsoft Yahei, Arial, Verdana;}#header {margin-left:30px;margin-bottom:20px;font-size:13px; /*generated by program*/color:#C8C8C8;}#content {position:relative;line-height:27px;font-weight:normal;font-size:";
	public final static String size_HTML_color = "px;}#line-number-wrap {position:absolute;top:0px;left:0px;width:50px;background-color:#F2F2F2;text-align:right;color:#222;}#line-number-wrap .line-number {height:27px;margin-right:10px;}#code-wrap {position:absolute;top:0px;left:60px;}label.keyword {color:#";
	public final static String color_HTML_code = ";}label.comment {color:green;}label.function-line {border-left:1px solid #C8C8C8;}</style></head><body><div id=\"header\"><p>This file is generated by code2Html.</p></div><div id=\"content\"><!--code start--><pre id=\"code-wrap\">";
	public final static String code_HTML_line = "</pre><!--code end--><div id=\"line-number-wrap\">";
	public final static String line_HTML = "</div></div><div style=\"width:100%;clear:both\"></div></body></html>";
	public final static String lineDIVPrefix = "<div class=\"line-number\">";
	public final static String LineDIVsuffix = "</div>";
	
	/*
	 * the C language
	 * */
	public static class C extends Source {
		public final String keyword = "\\b(?:auto|break|case|char|const|continue|default|do|double|else|enum|extern|float|for|goto|if|int|long|register|return|short|signed|sizeof|static|struct|switch|typedef|union|unsigned|void|volatile|while)\\b";
		public final String singleComment = "//[^\\r\\n]*+";
		public final String mutiComment = "/\\*[^*]*\\*+(?:[^/*][^*]*\\*+)*/";
		public final String tab = "\\t";
		/* (non-Javadoc)
		 * @see Schema.Source#getKeyword()
		 */
		@Override
		public String getKeyword() {
			// TODO Auto-generated method stub
			return keyword;
		}
		/* (non-Javadoc)
		 * @see Schema.Source#getSingleComment()
		 */
		@Override
		public String getSingleComment() {
			// TODO Auto-generated method stub
			return singleComment;
		}
		/* (non-Javadoc)
		 * @see Schema.Source#getMutiComment()
		 */
		@Override
		public String getMutiComment() {
			// TODO Auto-generated method stub
			return mutiComment;
		}
		
	}
	
	/*
	 * the Java language
	 * */
	public static class Java extends Source {
		public final String keyword = "\\b(?:abstract|super|assert|else|interface|switch|synchronized|break|extends|native|this|for|new|throw|case|final|package|throws|catch|finally|private|transient|protected|try|class|goto|public|void|const|if|return|volatile|continue|implements|short|while|default|import|static|do|instanceof|strictfp|double|int|long|boolean|enum|byte|char|float)\\b";
		public final String singleComment = "//[^\\r\\n]*+";
		public  final String mutiComment = "/\\*[^*]*\\*+(?:[^/*][^*]*\\*+)*/";
		/* (non-Javadoc)
		 * @see Schema.Source#getKeyword()
		 */
		@Override
		public String getKeyword() {
			// TODO Auto-generated method stub
			return keyword;
		}
		/* (non-Javadoc)
		 * @see Schema.Source#getSingleComment()
		 */
		@Override
		public String getSingleComment() {
			// TODO Auto-generated method stub
			return singleComment;
		}
		/* (non-Javadoc)
		 * @see Schema.Source#getMutiComment()
		 */
		@Override
		public String getMutiComment() {
			// TODO Auto-generated method stub
			return mutiComment;
		}
		
	}
}